### ISSUE TITLE
`(a)->` (no space)  potential benefit

### ISSUE THREAD

**Issue by lydell** [polarmobile/coffeescript-style-guide#11]
> When declaring a function that takes arguments, always use a single space after the closing parenthesis of the arguments list:
>
>    foo = (arg1, arg2) -> # Yes
>    foo = (arg1, arg2)-> # No

I prefer the `(a) ->` (space) style (I think), possibly mainly because most (all?) CoffeeScript code I've seen uses it. However, I recently ran into this problem:

I wanted to do this:
```coffeescript
asyncFunc (result) ->
  console.log result
```
But I somehow messed up and lost a space:
```coffeescript
asyncFunc(result) ->
  console.log result
```
Woops! Still valid code, though, but now it does something entirely different. Took me some time to spot.

If I had used a `(a)->` (no space) style, I could have solved it much faster, since the following is a syntax error:
```coffeescript
asyncFunc(result)->
  console.log result
```
Luckily, many (async) functions take another argument first.
```coffeescript
asyncFunc 3000, (result) ->
  console.log result
```

Any thoughts?

**Comment by anonomis** [comment]
Messing up this is like forgetting to add a space after punctuation.Most people react strongly upon breaking this convention in regular written language. A space before or after a parenthesis is even easier () to detect( ).
